### ISSUE TITLE
CV_Cam - fix video format

### ISSUE THREAD

**Issue by snaens** [Bento-Robotics/start_cameras#2]
CV_Cam (120fps) has broken video, probably using the wrong video format.
https://github.com/ros-drivers/usb_cam/tree/ros2#driver-supported-formats

change the camera parameter file to fix

**Comment by snaens** [comment]
params that worked on my machine:
```yml
/**:
    ros__parameters:
      video_device: "/dev/video2"
      framerate: 120.0
      #io_method: "mmap"
      frame_id: "camera"
      pixel_format: "mjpeg2rgb"  # see usb_cam/supported_formats for list of supported formats
      image_width: 1280
      image_height: 720
      camera_name: "camera0"
      #camera_info_url: "package://usb_cam/config/camera_info.yaml"
      #brightness: -1
      #contrast: -1
      #saturation: -1
      #sharpness: -1
      #gain: -1
      #auto_white_balance: true
      #white_balance: 4000
      #autoexposure: true
      #exposure: 100
      #autofocus: true
      #focus: -1
```
